version: '3'
services:
  service:
    # Если вы работаете на MacOS c процессором ARM, то в случае возникновения проблем при сборке образа,
    # связанных с установкой uwsgi, необходимо явно указать платформу скачиваемого образа.
    # https://docs.docker.com/build/building/multi-platform/
    # Раскомментируйте следующую строку.
    # platform: linux/amd64
    build: app
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - ./data:/data/:ro
    depends_on:
      - service
    ports:
      - "80:80"
